const products = [
  {
    id: 1,
    name: "Pixel Wave 12",
    category: "Phones",
    price: 449,
    description: "A 6.1-inch mid-range phone with a 2-day battery and a solid camera.",
  },
  {
    id: 2,
    name: "Orbit Pro Max",
    category: "Phones",
    price: 999,
    description: "Flagship phone with titanium frame, 120Hz display, and pro-grade cameras.",
  },
  {
    id: 3,
    name: "Nimbus Air 13",
    category: "Laptops",
    price: 1099,
    description: "Ultra-light 13-inch laptop, 18-hour battery, ideal for travel and writing.",
  },
  {
    id: 4,
    name: "Forge Studio 15",
    category: "Laptops",
    price: 1799,
    description: "15-inch creator laptop with discrete GPU for video editing and 3D work.",
  },
  {
    id: 5,
    name: "EchoBud Lite",
    category: "Audio",
    price: 59,
    description: "Budget wireless earbuds with 20-hour case battery and clear calls.",
  },
  {
    id: 6,
    name: "EchoBud Pro ANC",
    category: "Audio",
    price: 179,
    description: "Noise-cancelling earbuds with adaptive sound and wireless charging.",
  },
  {
    id: 7,
    name: "TrailCam 4K",
    category: "Cameras",
    price: 329,
    description: "Compact action camera with 4K60 video and waterproof housing.",
  },
  {
    id: 8,
    name: "Lumen R6 Mirrorless",
    category: "Cameras",
    price: 1499,
    description: "Full-frame mirrorless camera for enthusiasts and semi-pro shooters.",
  },
  {
    id: 9,
    name: "PulseFit Band",
    category: "Wearables",
    price: 79,
    description: "Lightweight fitness band tracking sleep, heart rate, and workouts.",
  },
  {
    id: 10,
    name: "PulseFit Watch S",
    category: "Wearables",
    price: 249,
    description: "Smartwatch with GPS, ECG sensor, and a bright always-on display.",
  },
  {
    id: 11,
    name: "DeskPad Mini Hub",
    category: "Accessories",
    price: 39,
    description: "Compact USB-C hub with HDMI, SD card reader, and fast charging.",
  },
  {
    id: 12,
    name: "GlideKey Mechanical",
    category: "Accessories",
    price: 129,
    description: "Compact mechanical keyboard with hot-swappable switches, wireless.",
  },
  {
    id: 13,
    name: "Vantage Monitor 27",
    category: "Monitors",
    price: 329,
    description: "27-inch 4K monitor with USB-C power delivery, great for a desk setup.",
  },
  {
    id: 14,
    name: "ArcBeam Speaker",
    category: "Audio",
    price: 99,
    description: "Portable Bluetooth speaker with 12-hour battery and deep bass.",
  },
];

export default products;
